PROGRAM := main
ST_SOURCES := main_counter_fb.st main.st
WRAPPER_CPP := custom_logic_wrapper.cpp
EXTRA_CPP_SOURCES := machine_helper.cpp
ECMC_PLUGIN_STRUCPP ?= ../../../ecmc_plugin_strucpp
include $(ECMC_PLUGIN_STRUCPP)/templates/strucpp_ioc_logic.make
